name: Main Workflow

on: 
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/node_setup

  tests:
    name: Lint, and line coverage
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/node_setup 
    - name: Linting
      run: npm run lint

    - name: Unit tests and coverage
      run: npm run test:coverage

  pkg-build:
    name: Building NPM package
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/node_setup
    - name: Build package
      run: npm pack

  pkg-test:
    name: Testing NPM package
    runs-on: ubuntu-latest
    needs: pkg-build

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/node_setup
    - name: Testing NPM package
      run: echo "Testing NPM package placeholder"
  
  publish:
    name: Publishing NPM package
    runs-on: ubuntu-latest
    needs: pkg-test

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/node_setup
    - name: Publishing NPM package
      run: echo "Publishing NPM package placeholder"
      
    
