name: Release Workflow

on:
  workflow_dispatch:

jobs:
  release:
    name: Release NPM package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/node_setup
    - name: Semantic Release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release